---
# tasks file for prod
- name: Install tomcat & java
  apt: name={{ item }} state=present
  with_items:
    - tomcat9
    - default-jdk

- name: Ensure tomcat is started
  service:  
    name: tomcat9
    state: started

- name: Copy artefact to tomcat
  synchronize:
    src: /tmp/hello-1.0.war
    dest: /var/lib/tomcat*/webapps/